groups:
  - research_associates:
    label: Research Associates
    summary: Academics and professionals who are working or have worked on research projects or other initiatives of The Visible College.
    members:
    - name: Christian Peters, Ph.D.
      id: christianpeters
      title: Managing Director, Bremen International Graduate School of Social Sciences (BIGSSS), University of Bremen
      image: christianpeters.jpg
      bio: people/bio/christianpeters.md
    - name: Janis Whitlock, Ph.D., M.P.H.
      id: janiswhitlock
      title: Research Scientist Emerita
      image: janiswhitlock.jpg
      bio: people/bio/janiswhitlock.md
    - name: Jed Verity, Ph.D.
      title: Ph.D. in Tibetan Buddhism
      image: jedverity.jpg
      bio: people/bio/jedverity_research.md
    - name: John L. Roberts, Ph.D.
      id: johnlroberts
      title: Associate Professor of Psychology, University of West Georgia
      image: johnlroberts.jpg
      bio: people/bio/johnlroberts.md
    - name: Justin Sui, Ph.D.
      id: justinsui
      title:
      image: justinsui.jpg
      bio: people/bio/justinsui.md
    - name: Steven Brown, Ph.D.
      id: stevenbrown
      title: Associate Professor of Teaching Philosophy, The Ohio State University
      image: stevenbrown.jpg
      bio: people/bio/stevenbrown_research.md
    - name: Tania Searle, Ph.D.
      id: taniasearle
      image: taniasearle.jpg
      bio: people/bio/taniasearle.md
  # - affiliates:
  #   label: Affiliates
  #   summary: Individuals who have contributed to the efforts of The Visible College in some form or another. Coming soon!
  #   members:
  - public_figures:
    label: Public Figures
    summary: Scholars working publicly in UAP Studies or adjacent fields who are not directly associated with The Visible College, but whose work we consider integral to an understanding of the subject area as a whole.
    members:
    - name: Alexander Wendt, Ph.D.
      id: alexanderwendt
      title: Mershon Professor of International Security and Professor of Political Science, Ohio State
      image: alexanderwendt.jpg
    - name: Avi Loeb, Ph.D.
      id: aviloeb
      title: Frank B. Baird Jr. Professor of Science, Harvard University
      image: aviloeb.jpg
    - name: Beatriz Villarroel, Ph.D.
      id: beatrizvillarroel
      title: Astronomy Researcher at the Nordic Institute for Theoretical Physics
      image: beatrizvillarroel.jpg
    - name: Christopher "Kit" Green, M.D., Ph.D.
      title: Professor in Forensic Neuroimaging, Department of Psychiatry and Behavioral Neurosciences, Wayne State University Medical School and Detroit Medical Center<br/>Former Senior Division Analyst for Neurosciences, Central Intelligence Agency (CIA)
      id: christophergreen
      image: christophergreen.jpg
    - name: Diana Walsh Pasulka, Ph.D.
      id: dianawalshpasulka
      title: Professor of Religious Studies, University of North Carolina, Wilmington
      image: dianawalshpasulka.jpg
    - name: Garry P. Nolan, Ph.D.
      id: garrypnolan
      title: Executive Director of the Board, <a href='https://thesolfoundation.org/'>Sol Foundation</a><br/>Professor in the Department of Pathology, <a href='https://med.stanford.edu/profiles/garry-nolan'>Stanford University School of Medicine</a>
      image: garrypnolan.jpg
    - name: J. Allen Hynek, Ph.D.
      id: jallenhynek
      title: Astronomer, Scientific Advisor to the US Air Force - Project Sign, Project Grudge, and Project Blue Book
      image: jallenhynek.jpg
    - name: Jacques Vallee, Ph.D.
      id: jacquesvallee
      title:  Computer scientist, venture capitalist, author, ufologist, and astronomer
      image: jacquesvallee.jpg
    - name: James E. McDonald, Ph.D.
      id: jamesemcdonald
      title: Physicist, Professor of Atmospheric Sciences
      image: jamesemcdonald.gif
    - name: Kevin Knuth, Ph.D.
      id: kevinknuth
      title: Professor of Physics, University at Albany
      image: kevinknuth.jpg
    - name: Michio Kaku, Ph.D.
      id: michiokaku
      title: Theoretical Physicist
      image: michiokaku.jpg
    - name: Stephen Finley, Ph.D.
      id: stephenfinley
      title: Chair of African and African American Studies, Louisiana State University
      image: stephenfinley.jpg
    - name: Timothy Gallaudet, Ph.D.
      id: timothygallaudet
      title: Former Rear Admiral, U.S. Navy<br/>Former Administrator, National Ocean and Atmospheric Administration (NOAA)
      image: timothygallaudet.jpg


    # - name: Richard M. Dolan, M.A.
    #   id: richardmdolan
    #   title: Researcher, historian, and writer
    #   image: richardmdolan.jpg