groups:
  - research_associates:
    label: Research Associates
    members:
    - name: Albert Einstein
      id: einstein
      align: left
      title: Professor, UVa
      image: prof_pic.jpg
      bio: people/bio/einstein_short.md
    - name: Albert Einstein
      id: einstein
      align: left
      image: prof_pic.jpg
      bio: people/bio/einstein.md
  - affiliates:
    label: Affiliates
    members:
    - name: Albert Einstein
      id: einstein
      align: left
      image: prof_pic.jpg
      bio: people/bio/einstein.md
  - public_figures:
    label: Public Figures
    members:
    - name: Albert Einstein
      id: einstein
      align: left
      image: prof_pic.jpg
      bio: people/bio/einstein.md