groups:
  - research_associates:
    label: Research Associates
    summary: Academics and professionals who are working or have worked on research projects or other initiatives of The Visible College.
    members:
    - name: Albert Einstein
      id: einstein
      align: left
      title: Professor, UVa
      image: prof_pic.jpg
      bio: people/bio/einstein_short.md
    - name: Albert Einstein
      id: einstein
      align: left
      image: prof_pic.jpg
      bio: people/bio/einstein.md
  - affiliates:
    label: Affiliates
    summary: Individuals who have contributed to the efforts of The Visible College in some form or another.
    members:
    - name: Albert Einstein
      id: einstein
      align: left
      image: prof_pic.jpg
      bio: people/bio/einstein.md
  - public_figures:
    label: Public Figures
    summary: Scholars working publicly in UAP Studies or adjacent fields who are <b>not</b> associated with The Visible College, but whose work we consider integral to an understanding of the subject area as a whole.
    members:
    - name: Albert Einstein
      id: einstein
      align: left
      image: prof_pic.jpg
      bio: people/bio/einstein.md