groups:
  - research_associates:
    label: Research Associates
    members:
    - name: Albert Einstein
      align: left
      title: Professor, UVa
      image: prof_pic.jpg
      bio: bio/einstein.md
      image_circular: false # crops the image to make it circular
      more_info:
    - name: Albert Einstein
      align: left
      image: prof_pic.jpg
      bio: bio/einstein.md
      image_circular: false # crops the image to make it circular
      more_info:
  - affiliates:
    label: Affiliates
    members:
    - name: Albert Einstein
      align: left
      image: prof_pic.jpg
      bio: bio/einstein.md
      image_circular: false # crops the image to make it circular
      more_info:
  - public_figures:
    label: Public Figures
    members:
    - name: Albert Einstein
      align: left
      image: prof_pic.jpg
      bio: bio/einstein.md
      image_circular: false # crops the image to make it circular
      more_info: